// Code generated by "stringer -type=FspPositionType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OutMordor-0]
	_ = x[InMordor-1]
}

const _FspPositionType_name = "OutMordorInMordor"

var _FspPositionType_index = [...]uint8{0, 9, 17}

func (i FspPositionType) String() string {
	if i < 0 || i >= FspPositionType(len(_FspPositionType_index)-1) {
		return "FspPositionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FspPositionType_name[_FspPositionType_index[i]:_FspPositionType_index[i+1]]
}
